In [11]:
#import bin-encoding data
import pandas as pd
import numpy as np
import scipy.stats as stats
import sklearn
import random
import os
from pathlib import Path
from sklearn.linear_model import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import average_precision_score, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report 
from sklearn.metrics.pairwise import cosine_similarity


In [12]:
def LoadData(filename):
    DATA_DIR = "Data"
    ENCODING_DIR = os.path.join(DATA_DIR, filename)
    data = pd.read_csv(ENCODING_DIR, index_col=[0])
    return data


In [13]:
filename = "binEncoding.csv"

In [14]:
X = LoadData(filename)
Temp = X.drop(columns=['article_id'])
X.head()

target  company  central  retailer  inflation  stores  bank  child  \
0       1        1        1         1          1       1     1      1   
1       1        1        1         1          1       1     1      1   
2       0        0        0         0          0       0     0      0   
3       0        0        0         0          0       0     0      0   
4       0        0        0         0          0       0     0      0   

   commerce  online     ...      advises  softer  reported  homeless  lining  \
0         1       1     ...            0       0         0         0       0   
1         1       1     ...            0       0         0         0       0   
2         0       0     ...            0       0         0         0       0   
3         0       0     ...            0       0         0         0       0   
4         0       0     ...            0       0         0         0       0   

   liberal  marketplace  gartner  indonesian  article_id  
0        0            0        0           0         125  
1        0            0        0           0          69  
2        0            0        0           0          32  
3        0            0        0           0         162  
4        0            0        0           0          49  

[5 rows x 251 columns]

In [15]:
#Similarity matrix between each article
Csim = cosine_similarity(Temp)

#convert to numpy
npV = np.asarray(Csim)
print(npV)
rows = np.size(npV,0)
print(rows)

#print(Csim)
#print(len(Csim))



[[1.         1.         0.         0.         0.         1.
  0.         0.22941573 0.22941573 0.22941573 0.         0.22941573
  0.32444284 0.         0.22941573 0.         0.22941573 0.32444284
  0.22941573 0.22941573 0.        ]
 [1.         1.         0.         0.         0.         1.
  0.         0.22941573 0.22941573 0.22941573 0.         0.22941573
  0.32444284 0.         0.22941573 0.         0.22941573 0.32444284
  0.22941573 0.22941573 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.       

In [16]:
Y = X
#Y['relatedArticles'] = 0
#Y['SecondRelated'] = 0
#Y['ThirdRelated'] = 0
Y.head(10)

target  company  central  retailer  inflation  stores  bank  child  \
0       1        1        1         1          1       1     1      1   
1       1        1        1         1          1       1     1      1   
2       0        0        0         0          0       0     0      0   
3       0        0        0         0          0       0     0      0   
4       0        0        0         0          0       0     0      0   
5       1        1        1         1          1       1     1      1   
6       0        0        0         0          0       0     0      0   
7       0        0        1         0          0       0     0      0   
8       0        0        1         0          0       0     0      0   
9       0        1        0         0          0       0     0      0   

   commerce  online     ...      advises  softer  reported  homeless  lining  \
0         1       1     ...            0       0         0         0       0   
1         1       1     ...            0       0         0         0       0   
2         0       0     ...            0       0         0         0       0   
3         0       0     ...            0       0         0         0       0   
4         0       0     ...            0       0         0         0       0   
5         1       1     ...            0       0         0         0       0   
6         0       0     ...            0       0         0         0       0   
7         0       0     ...            0       0         0         0       0   
8         0       0     ...            0       0         0         0       0   
9         0       0     ...            0       0         0         0       0   

   liberal  marketplace  gartner  indonesian  article_id  
0        0            0        0           0         125  
1        0            0        0           0          69  
2        0            0        0           0          32  
3        0            0        0           0         162  
4        0            0        0           0          49  
5        0            0        0           0          22  
6        0            0        0           0          36  
7        0            0        0           0          99  
8        0            0        0           0          94  
9        0            0        0           0          58  

[10 rows x 251 columns]

In [19]:
for i in range(rows):
    #find most related articles indexed
    a = npV[i,:]
    index = np.argpartition(a, -4)[-4:]
    index2= index[np.argsort(a[index])]
    
    #show the index in X matrix
    print(i)
    print(index)
    print(index2)
    #show the similarity value
    print(a[index2])
    related = []
    related.append(str(X.iloc[index2[2]]['article_id']))
    related.append(str(X.iloc[index2[1]]['article_id']))
    related.append(str(X.iloc[index2[0]]['article_id']))
    
    
    Y.at[i, 'related_articles'] = ', '.join(related)
    
    Final = Y[['article_id', 'related_articles']]
    #Put into table Y
    #Y.at[i, 'FirstRelated'] = FirstID
    #Y.at[i, 'SecondRelated'] = SecondID
    #Y.at[i,'ThirdRelated'] = ThirdID
    

0
[17  5  1  0]
[17  5  1  0]
[0.32444284 1.         1.         1.        ]
1
[17  5  1  0]
[17  5  1  0]
[0.32444284 1.         1.         1.        ]
2
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
3
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
4
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
5
[17  5  1  0]
[17  5  1  0]
[0.32444284 1.         1.         1.        ]
6
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
7
[ 0 12  7  8]
[ 0 12  7  8]
[0.22941573 0.70710678 1.         1.        ]
8
[ 0 12  7  8]
[ 0 12  7  8]
[0.22941573 0.70710678 1.         1.        ]
9
[1 5 9 0]
[1 5 0 9]
[0.22941573 0.22941573 0.22941573 1.        ]
10
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
11
[ 1 16 11  0]
[ 1  0 16 11]
[0.22941573 0.22941573 1.         1.        ]
12
[ 0  7 12  8]
[ 0  7  8 12]
[0.32444284 0.70710678 0.70710678 1.        ]
13
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
14
[ 1  5 14  0]
[ 1  5  0 14]
[0.22941573 0.22941573 0.22941573 1.        ]
15
[ 7  9  8 20]
[ 7  9  8 20]
[0. 0. 0. 0.]
16
[ 1 16 

In [8]:
Final.head()

article_id related_articles
0         125       22, 69, 49
1          69       22, 69, 49
2          32       94, 58, 99
3         162       94, 58, 99
4          49       94, 58, 99